CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO mc_database;

-- Table structure for table `make`
CREATE TABLE public.make (
	make_id INT GENERATED BY DEFAULT AS IDENTITY,
	make_name CHARACTER VARYING NOT NULL,
	CONSTRAINT make_pk PRIMARY KEY (make_id)
);

-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    make_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between `make` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_make FOREIGN KEY (make_id)
	REFERENCES public.make (make_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Data for table `make`
INSERT INTO public.make (make_name)
VALUES ('Chevrolet'),
	('Ford'),
	('Dodge');


UPDATE inventory SET inv_image = REPLACE(inv_image,'/images/', '/images/vehicles/');
UPDATE inventory SET inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');